/**
 * MinionsConfig Type Definitions (v2.0 Schema)
 *
 * This module defines the TypeScript interfaces for the minions.json configuration file.
 * The minions.json file is the single configuration file for a project using the Minions framework.
 *
 * @see Section 2.1.1 of the engineering design document for the full schema specification.
 */

/**
 * Project configuration within MinionsConfig.
 * Contains basic project identification and branch settings.
 */
export interface MinionsConfigProject {
  /** Human-readable project name */
  name: string

  /** Default branch to use as base for new agent worktrees (e.g., 'main', 'develop'). Optional for non-git projects. */
  defaultBaseBranch?: string

  /** Optional project description, typically auto-generated by the setup wizard */
  description?: string
}

/**
 * Setup configuration within MinionsConfig.
 * Defines how worktrees are initialized and what commands to run.
 */
export interface MinionsConfigSetup {
  /**
   * Files to copy from the main project to each worktree.
   * Common examples: '.env.example', '.nvmrc', '.env.local'
   * These are simple file paths relative to project root.
   */
  filesToCopy: string[]

  /**
   * Commands to run after worktree creation.
   * Typically package installation or build preparation.
   * Examples: 'npm install', 'pip install -r requirements.txt'
   */
  postSetupCommands: string[]

  /**
   * Commands to run before worktree creation for validation.
   * Preserved from legacy config for backward compatibility.
   * Examples: 'git status', 'npm audit'
   */
  preflightCommands?: string[]

  /**
   * Files that must exist for the project to be valid.
   * Preserved from legacy config for backward compatibility.
   * Examples: 'package.json', 'Cargo.toml', 'go.mod'
   */
  requiredFiles?: string[]

  /** Command to build the project (e.g., 'npm run build', 'cargo build') */
  buildCommand?: string

  /** Command to run tests (e.g., 'npm test', 'pytest') */
  testCommand?: string

  /** Command to lint the project (e.g., 'npm run lint', 'cargo clippy') */
  lintCommand?: string

  /**
   * Test environment commands to run for each agent.
   * These are background processes like dev servers, watchers, etc.
   */
  testEnvironments?: Array<{
    id: string
    name: string
    command: string
    cwd?: string
    port?: number
  }>
}

/**
 * Detection metadata within MinionsConfig.
 * Populated by the setup wizard when analyzing the project.
 */
export interface MinionsConfigDetected {
  /**
   * Primary programming language detected.
   * Examples: 'typescript', 'python', 'go', 'rust', 'java'
   */
  language: string

  /**
   * Framework or library detected.
   * Examples: 'react', 'express', 'django', 'fastapi', 'gin'
   */
  framework?: string

  /**
   * Package manager detected.
   * Examples: 'npm', 'yarn', 'pnpm', 'pip', 'poetry', 'go mod', 'cargo'
   */
  packageManager?: string

  /** ISO timestamp when detection was performed */
  detectedAt: string
}

/**
 * Wizard completion metadata within MinionsConfig.
 * Records when and how the setup wizard configured the project.
 */
export interface MinionsConfigWizard {
  /** ISO timestamp when the wizard completed successfully */
  completedAt: string

  /** Session ID of the wizard agent, useful for debugging or reference */
  agentSessionId?: string
}

/**
 * Main MinionsConfig interface (v2.0 schema).
 *
 * This is the root interface for the minions.json configuration file.
 * It replaces the legacy minions/config.json file and provides a cleaner,
 * more minimal project footprint.
 *
 * @example
 * ```json
 * {
 *   "version": "2.0",
 *   "project": {
 *     "name": "my-app",
 *     "defaultBaseBranch": "main"
 *   },
 *   "setup": {
 *     "filesToCopy": [".env.example"],
 *     "postSetupCommands": ["npm install"],
 *     "buildCommand": "npm run build",
 *     "testCommand": "npm test"
 *   }
 * }
 * ```
 */
export interface MinionsConfig {
  /**
   * Schema version identifier. Must be '2.0' for the new format.
   * This allows for future migrations if the schema changes.
   */
  version: '2.0'

  /** Project identification and settings */
  project: MinionsConfigProject

  /** Worktree setup configuration */
  setup: MinionsConfigSetup

  /**
   * Auto-detected project metadata.
   * Populated by the setup wizard during project analysis.
   */
  detected?: MinionsConfigDetected

  /**
   * Wizard completion metadata.
   * Present if the project was configured via the setup wizard.
   */
  wizard?: MinionsConfigWizard
}

// =============================================================================
// Wizard Session Types
// =============================================================================

/**
 * Valid status values for a wizard session.
 */
export type WizardSessionStatus =
  | 'analyzing'   // Agent is exploring the project structure
  | 'questioning' // Agent is asking user questions
  | 'generating'  // Agent is generating the configuration
  | 'complete'    // Wizard finished successfully
  | 'cancelled'   // User cancelled the wizard
  | 'timeout'     // Wizard timed out waiting for response
  | 'error'       // An error occurred during wizard execution

/**
 * All valid wizard session status values as a readonly array.
 * Useful for validation and iteration.
 */
export const WIZARD_SESSION_STATUSES: readonly WizardSessionStatus[] = [
  'analyzing',
  'questioning',
  'generating',
  'complete',
  'cancelled',
  'timeout',
  'error'
] as const

/**
 * Default timeout for wizard sessions in milliseconds (5 minutes).
 */
export const DEFAULT_WIZARD_TIMEOUT_MS = 300000

/**
 * WizardSession interface.
 *
 * Tracks the state of the setup wizard during project initialization.
 * The wizard runs as a special agent that analyzes the project and
 * generates the minions.json configuration through natural language interaction.
 *
 * @see Section 3.4 of the engineering design document for session management details.
 */
export interface WizardSession {
  /** Unique identifier for this wizard session */
  id: string

  /** Absolute path to the project being configured */
  projectPath: string

  /** ID of the agent running the wizard */
  agentId: string

  /** Current status of the wizard session */
  status: WizardSessionStatus

  /**
   * Partial or complete configuration generated by the wizard.
   * May be incomplete during 'analyzing' or 'questioning' phases.
   */
  config?: Partial<MinionsConfig>

  /** Whether the wizard generated a CLAUDE.md file for the project */
  claudeMdGenerated?: boolean

  /** ISO timestamp when the wizard session started */
  startedAt: string

  /** Timeout duration in milliseconds (default: 300000 = 5 minutes) */
  timeoutMs: number

  /** Error message if status is 'error' or 'timeout' */
  error?: string
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Creates a default MinionsConfig with minimal required fields.
 *
 * @param name - Project name
 * @param defaultBaseBranch - Default base branch (e.g., 'main', 'develop')
 * @returns A valid MinionsConfig with sensible defaults
 *
 * @example
 * ```typescript
 * const config = createDefaultMinionsConfig('my-app', 'main')
 * // Returns:
 * // {
 * //   version: '2.0',
 * //   project: { name: 'my-app', defaultBaseBranch: 'main' },
 * //   setup: { filesToCopy: [], postSetupCommands: [] }
 * // }
 * ```
 */
export function createDefaultMinionsConfig(
  name: string,
  defaultBaseBranch?: string
): MinionsConfig {
  const project: MinionsConfigProject = { name }
  if (defaultBaseBranch !== undefined) {
    project.defaultBaseBranch = defaultBaseBranch
  }
  return {
    version: '2.0',
    project,
    setup: {
      filesToCopy: [],
      postSetupCommands: []
    }
  }
}

/**
 * Type guard to validate if an unknown value is a valid MinionsConfig.
 *
 * Performs runtime validation to ensure the object has all required fields
 * and correct structure. Useful for validating parsed JSON.
 *
 * @param value - Unknown value to validate
 * @returns True if value is a valid MinionsConfig
 *
 * @example
 * ```typescript
 * const parsed = JSON.parse(fileContents)
 * if (isValidMinionsConfig(parsed)) {
 *   // parsed is now typed as MinionsConfig
 *   console.log(parsed.project.name)
 * }
 * ```
 */
export function isValidMinionsConfig(value: unknown): value is MinionsConfig {
  if (value === null || value === undefined) {
    return false
  }

  if (typeof value !== 'object' || Array.isArray(value)) {
    return false
  }

  const obj = value as Record<string, unknown>

  // Check version
  if (obj.version !== '2.0') {
    return false
  }

  // Check project
  if (typeof obj.project !== 'object' || obj.project === null) {
    return false
  }
  const project = obj.project as Record<string, unknown>
  if (typeof project.name !== 'string') {
    return false
  }
  // defaultBaseBranch is optional (non-git projects may not have one), but if present must be a string
  if (project.defaultBaseBranch !== undefined && typeof project.defaultBaseBranch !== 'string') {
    return false
  }

  // Check setup
  if (typeof obj.setup !== 'object' || obj.setup === null) {
    return false
  }
  const setup = obj.setup as Record<string, unknown>
  if (!Array.isArray(setup.filesToCopy) || !Array.isArray(setup.postSetupCommands)) {
    return false
  }

  return true
}
