declare const api: {
    selectProject: (path: string) => Promise<any>;
    installFramework: (path: string) => Promise<any>;
    getRecentProjects: () => Promise<any>;
    getCurrentProject: () => Promise<any>;
    clearCurrentProject: () => Promise<any>;
    addProject: (path: string) => Promise<any>;
    removeProject: (path: string) => Promise<any>;
    switchProject: (path: string) => Promise<any>;
    getActiveProjects: () => Promise<any>;
    listAgents: () => Promise<any>;
    listAgentsForProject: (projectPath: string) => Promise<any>;
    stopAgent: (agentId: string) => Promise<any>;
    openInCursor: (agentId: string) => Promise<any>;
    clearUnread: (agentId: string) => Promise<any>;
    getSuperAgentDetails: (agentId: string) => Promise<any>;
    approvePlan: (superAgentId: string, planId: string) => Promise<any>;
    teardownAgent: (agentId: string, force: boolean) => Promise<any>;
    unassignAgent: (agentId: string) => Promise<any>;
    saveUIState: (agentId: string, uiState: any) => Promise<any>;
    retryResumeAgent: (agentId: string) => Promise<any>;
    startFreshSession: (agentId: string) => Promise<any>;
    sendTerminalInput: (agentId: string, data: string) => void;
    resizeTerminal: (agentId: string, cols: number, rows: number) => void;
    onTerminalOutput: (callback: (agentId: string, data: string) => void) => () => Electron.IpcRenderer;
    startPlainTerminal: (agentId: string, terminalId: string) => Promise<any>;
    stopPlainTerminal: (terminalId: string) => Promise<any>;
    sendPlainTerminalInput: (terminalId: string, data: string) => void;
    resizePlainTerminal: (terminalId: string, cols: number, rows: number) => void;
    onPlainTerminalOutput: (callback: (terminalId: string, data: string) => void) => () => Electron.IpcRenderer;
    onPlainTerminalWaitingForInput: (callback: (terminalId: string, promptText: string) => void) => () => Electron.IpcRenderer;
    onPlainTerminalResumedWork: (callback: (terminalId: string) => void) => () => Electron.IpcRenderer;
    getAssignments: () => Promise<any>;
    getAssignmentsForProject: (projectPath: string) => Promise<any>;
    createAssignment: (assignment: any) => Promise<any>;
    createAssignmentForProject: (projectPath: string, assignment: any) => Promise<any>;
    createSuperAssignment: (projectPath: string, assignment: any) => Promise<any>;
    teleportFromCloud: (projectPath: string, sessionId: string) => Promise<any>;
    updateAssignment: (assignmentId: string, updates: any) => Promise<any>;
    createPullRequest: (assignmentId: string, autoCommit?: boolean) => Promise<any>;
    checkPullRequestStatus: (assignmentId: string) => Promise<any>;
    detectPullRequest: (assignmentId: string, force?: boolean) => Promise<any>;
    startPRPolling: (assignmentId: string, subscriberId: string) => Promise<any>;
    stopPRPolling: (assignmentId: string, subscriberId: string) => Promise<any>;
    stopAllPRPolling: (subscriberId: string) => Promise<any>;
    refreshPRNow: (assignmentId: string) => Promise<any>;
    checkDependencies: () => Promise<any>;
    onAgentListUpdate: (callback: () => void) => () => Electron.IpcRenderer;
    onAssignmentsUpdate: (callback: () => void) => () => Electron.IpcRenderer;
    getAgentState: (agentId: string) => Promise<any>;
    onAgentStateChanged: (callback: (agentId: string, state: "working" | "waiting" | "unknown") => void) => () => Electron.IpcRenderer;
    onAgentWaitingForInput: (callback: (agentId: string, promptText: string) => void) => () => Electron.IpcRenderer;
    onAgentResumedWork: (callback: (agentId: string) => void) => () => Electron.IpcRenderer;
    onAgentAlreadyAttached: (callback: (agentId: string, details: { sessionName: string; message: string }) => void) => () => Electron.IpcRenderer;
    getClaudeSessionInfo: (agentId: string) => Promise<any>;
    onClaudeSessionInfoUpdated: (callback: (agentId: string, info: any) => void) => () => Electron.IpcRenderer;
    getSettings: () => Promise<any>;
    updateSettings: (updates: any) => Promise<any>;
    openFeedback: () => Promise<any>;
    // Terminal capabilities
    checkTmuxAvailable: () => Promise<boolean>;
    getTestEnvConfig: (agentId?: string) => Promise<any>;
    getTestEnvCommands: (agentId?: string, assignmentOverrides?: any[]) => Promise<any>;
    startTestEnv: (agentId: string, commandId?: string) => Promise<any>;
    stopTestEnv: (agentId: string, commandId?: string) => Promise<any>;
    getTestEnvStatus: (agentId: string) => Promise<any>;
    sendTestEnvInput: (agentId: string, commandId: string, data: string) => void;
    resizeTestEnv: (agentId: string, commandId: string, cols: number, rows: number) => void;
    onTestEnvOutput: (callback: (agentId: string, commandId: string, data: string) => void) => () => Electron.IpcRenderer;
    onTestEnvStarted: (callback: (agentId: string, commandId: string) => void) => () => Electron.IpcRenderer;
    onTestEnvStopped: (callback: (agentId: string, commandId: string) => void) => () => Electron.IpcRenderer;
    onTestEnvExited: (callback: (agentId: string, commandId: string, exitCode: number) => void) => () => Electron.IpcRenderer;
    validateTeleport: (agentId: string) => Promise<any>;
    onTeleportValidationFailed: (callback: (data: {
        agentId: string;
        reason: string;
        canRetry: boolean;
    }) => void) => () => Electron.IpcRenderer;
    onTeleportResumeFailed: (callback: (data: {
        agentId: string;
        reason: string;
    }) => void) => () => Electron.IpcRenderer;
    // Workflow APIs
    getWorkflowConfig: () => Promise<{ workflows: import('../main/services/types/WorkflowTypes').WorkflowConfig[] }>;
    getSubagentTypes: () => Promise<import('../main/services/types/WorkflowTypes').SubagentType[]>;
    getAllWorkflows: () => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig[]>;
    getActiveWorkflow: (projectPath: string) => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig>;
    getWorkflow: (workflowId: string) => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig | undefined>;
    createWorkflow: (name: string, description?: string) => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig>;
    updateWorkflow: (workflowId: string, updates: Partial<import('../main/services/types/WorkflowTypes').WorkflowConfig>) => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig>;
    deleteWorkflow: (workflowId: string) => Promise<void>;
    getWorkflowTemplates: () => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig[]>;
    saveWorkflowAsTemplate: (workflow: import('../main/services/types/WorkflowTypes').WorkflowConfig, name: string) => Promise<import('../main/services/types/WorkflowTypes').WorkflowConfig>;
    // Setup Wizard APIs
    checkWizard: (projectPath: string) => Promise<{
        needsWizard: boolean;
        hasLegacy: boolean;
    }>;
    startWizard: (projectPath: string) => Promise<import('../main/services/types/MinionsConfig').WizardSession>;
    cancelWizard: (sessionId: string) => Promise<void>;
    finalizeWizard: (projectPath: string, config: import('../main/services/types/MinionsConfig').MinionsConfig) => Promise<void>;
    quickSetup: (projectPath: string) => Promise<void>;
    migrateProject: (projectPath: string) => Promise<import('../main/services/types/MinionsConfig').MinionsConfig>;
    // Archive APIs
    listArchivedAgents: (projectPath?: string) => Promise<import('../main/services/types/ProjectConfig').ArchivedAgent[]>;
    getArchivedAgent: (projectPath: string, archiveId: string) => Promise<import('../main/services/types/ProjectConfig').ArchivedAgent | null>;
    restoreArchivedAgent: (projectPath: string, archiveId: string) => Promise<import('../main/services/types/ProjectConfig').AgentInfo>;
    // Claude Config APIs
    checkClaudeCode: () => Promise<boolean>;
    scanClaudeConfig: () => Promise<import('../main/services/types/ClaudeConfigTypes').ClaudeConfigScanResult>;
    refreshClaudeConfig: () => Promise<import('../main/services/types/ClaudeConfigTypes').ClaudeConfigScanResult>;
    getClaudeConfigEnabled: () => Promise<boolean>;
    getClaudeConfigSettings: () => Promise<import('../main/services/types/ClaudeConfigTypes').ClaudeConfigSettings>;
    setClaudeConfigEnabled: (updates: Partial<import('../main/services/types/ClaudeConfigTypes').ClaudeConfigSettings>) => Promise<import('../main/services/types/ClaudeConfigTypes').ClaudeConfigSettings>;
    getClaudeConfigScanResult: () => Promise<import('../main/services/types/ClaudeConfigTypes').ClaudeConfigScanResult>;
    onClaudeConfigUpdated: (callback: (result: import('../main/services/types/ClaudeConfigTypes').ClaudeConfigScanResult) => void) => () => Electron.IpcRenderer;
    // Skills Library APIs
    scanSkillsLibrary: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').LibraryScanResult>;
    getSkillsLibraryScanResult: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').LibraryScanResult>;
    refreshSkillsLibrary: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').LibraryScanResult>;
    getSkillsLibrarySettings: () => Promise<import('../main/services/types/SkillsLibraryTypes').SkillsLibrarySettings>;
    updateSkillsLibrarySettings: (updates: Partial<import('../main/services/types/SkillsLibraryTypes').SkillsLibrarySettings>) => Promise<import('../main/services/types/SkillsLibraryTypes').SkillsLibrarySettings>;
    getEnabledSkills: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').ItemDefinition[]>;
    // Unified Skills APIs
    scanUnifiedSkills: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').UnifiedScanResult>;
    getUnifiedSkillsScanResult: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').UnifiedScanResult>;
    refreshUnifiedSkills: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').UnifiedScanResult>;
    getUnifiedEnabledSkills: (projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').UnifiedItem[]>;
    getSkillById: (skillId: string, projectPath?: string) => Promise<import('../main/services/types/SkillsLibraryTypes').UnifiedItem | undefined>;
    setSkillEnabled: (skillId: string, enabled: boolean) => Promise<void>;
    getSkillsAsSubagentTypes: (projectPath?: string) => Promise<import('../main/services/types/WorkflowTypes').SubagentType[]>;
    onSkillsLibraryUpdated: (callback: (result: import('../main/services/types/SkillsLibraryTypes').LibraryScanResult) => void) => () => Electron.IpcRenderer;
    onUnifiedSkillsUpdated: (callback: (result: import('../main/services/types/SkillsLibraryTypes').UnifiedScanResult) => void) => () => Electron.IpcRenderer;
};
export type ElectronAPI = typeof api;
export {};
